### PR TITLE
fix(#66): signals as refs

### LINKED ISSUE #66: ref ins rsbuild failed
### Describe the bug

I saw this in solidjs-use.
But failed in rsbuild.
I don't know the reason why this report is wrong.
Solidjs-use is written wrong.
Or.
Rsbuild was wrong.
[https://github.com/web-infra-dev/rsbuild/issues/1963](https://github.com/web-infra-dev/rsbuild/issues/1963)

### Your Example Website or App

https://github.com/web-infra-dev/rsbuild/issues/1963

### Steps to Reproduce the Bug or Issue

[https://github.com/web-infra-dev/rsbuild/issues/1963](https://github.com/web-infra-dev/rsbuild/issues/1963)

### Expected behavior

[https://github.com/web-infra-dev/rsbuild/issues/1963](https://github.com/web-infra-dev/rsbuild/issues/1963)

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wjq990112**
Closes #66

### CODE REVIEW

**Comment by lxsmnsyc** [comment]
Thanks. I honestly thought it would work initially.

File: src/babel/core/transform-jsx.ts [hunk 1]
```diff
@@ -91,11 +95,17 @@ function extractJSXExpressionFromRef(
                   t.callExpression(unwrappedIdentifier, [arg]),
                 ),
               ]),
-              t.blockStatement([
-                t.expressionStatement(
-                  t.assignmentExpression('=', unwrappedIdentifier, arg),
-                ),
-              ]),
+              // fix the new usage of `ref` attribute,
+              // if use `Signals as refs`, the `else` branch will throw an errow with `Cannot assign to "setter" because it is a constant` message
```
Comment (vincentfretin) [inline src/babel/core/transform-jsx.ts:99]: typo errow => error

Comment (wjq990112) [reply src/babel/core/transform-jsx.ts:99]: I'm sorry, I'll fix it.
